export const STORE_CATEGORIES = {
  physical: [
    "Fashion & Clothing",
    "Beauty & Cosmetics",
    "Jewelry & Accessories",
    "Shoes & Footwear",
    "Phones & Gadgets",
    "Electronics",
    "Home & Furniture",
    "Food & Drinks",
    "Health & Wellness",
    "Fitness & Gym",
    "Baby Products",
    "Books & Stationery",
    "Automobile",
    "Agriculture",
    "Pets & Animals",
    "Supermarket",
    "Gift Shop",
    "Furniture",
    "Sports Equipment",
    "Other",
  ],

  digital: [
    "Ebooks",
    "Online Courses",
    "Coaching",
    "Consulting",
    "Digital Marketing",
    "Graphics Design",
    "Web Development",
    "UI/UX Design",
    "Software & SaaS",
    "Templates",
    "Music & Audio",
    "Photography",
    "Video Editing",
    "Content Creation",
    "Social Media Services",
    "Crypto & Forex",
    "AI Tools",
    "Freelancing",
    "Writing Services",
    "Other",
  ],
};
