import { useMemo } from "react";
import { Badge, EmptyState, PageHeader } from "../components/UI";
import styles from "../styles/v11.module.css";
import { Link2 } from "lucide-react";

export function AnalyticsPage({ links, history }) {
  const grouped = useMemo(() => links.map((link) => ({ link, events: history.filter((item) => String(item.linkId?._id || item.linkId) === String(link._id)) })).sort((a, b) => b.events.length - a.events.length), [links, history]);
  const last30 = history.filter((event) => Date.now() - new Date(event.createdAt).getTime() <= 30 * 86400000);
  const days = Array.from({ length: 14 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (13 - index)); return { date, count: history.filter((event) => new Date(event.createdAt).toDateString() === date.toDateString()).length }; });
  const max = Math.max(...days.map((day) => day.count), 1);
  return <div className={styles.page}><PageHeader eyebrow="LINK INSIGHTS" title="Real traffic, without invented metrics." description="These numbers come directly from recorded smart-link click history."/><div className={styles.metricRow}><div><span>Recorded clicks</span><b>{history.length.toLocaleString()}</b></div><div><span>Last 30 days</span><b>{last30.length.toLocaleString()}</b></div><div><span>Links with traffic</span><b>{grouped.filter((group) => group.events.length).length}</b></div></div>{history.length ? <><section className={styles.chartPanel}><h2>Clicks over the last 14 days</h2><div className={styles.barChart}>{days.map((day) => <div key={day.date.toISOString()}><span style={{ height: `${Math.max((day.count / max) * 100, day.count ? 8 : 2)}%` }}/><small>{day.date.toLocaleDateString(undefined, { day: "numeric", month: "short" })}</small><b>{day.count}</b></div>)}</div></section><section className={styles.section}><div className={styles.sectionTitle}><h2>Traffic by smart link</h2></div><div className={styles.dataList}>{grouped.map(({ link, events }) => <article key={link._id}><span className={styles.assetIcon}><Link2/></span><span className={styles.itemIdentity}><b>{link.title || "Untitled link"}</b><small>{link.linkType || "WhatsApp"}</small></span><span><small>Recorded clicks</small><b>{events.length || link.redirectCount || 0}</b></span><Badge tone={events.length ? "success" : "neutral"}>{events.length ? "Has traffic" : "No traffic"}</Badge></article>)}</div></section></> : <EmptyState title="No recorded traffic yet" description="Share a smart link. Recorded click activity will appear here—V1.1 will not fabricate analytics."/>}</div>;
}
