import { useMemo, useState } from "react";
import { useRouter } from "next/router";
import { Badge, Button, EmptyState, PageHeader } from "../components/UI";
import { v11Api } from "../lib/api";
import styles from "../styles/v11.module.css";

export function PagesPage({ pages, leads, refresh, onCreate, onLeads }) {
  const router = useRouter(); const [query, setQuery] = useState(""), [error, setError] = useState("");
  const filtered = useMemo(() => pages.filter((page) => `${page.title} ${page.slug}`.toLowerCase().includes(query.toLowerCase())), [pages, query]);
  const remove = async (page) => { if (!window.confirm(`Delete “${page.title}”? This cannot be undone.`)) return; try { await v11Api.deletePage(page._id); await refresh(); } catch (e) { setError(e.message); } };
  return <div className={styles.page}><PageHeader eyebrow="LANDING PAGES" title="Turn interest into action." description="Manage campaign pages, offer pages, lead capture and WhatsApp conversion experiences." actions={<Button onClick={onCreate}>＋ Create landing page</Button>}/><div className={styles.metricRow}><div><span>Landing pages</span><b>{pages.length}</b></div><div><span>Published</span><b>{pages.filter((page) => page.slug).length}</b></div><div><span>Leads collected</span><b>{leads.length}</b></div></div><div className={styles.toolbar}><label className={styles.search}>⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search landing pages"/></label></div>{error && <p className={styles.inlineError}>{error}</p>}
    {filtered.length ? <div className={styles.assetGrid}>{filtered.map((page) => { const pageLeads = leads.filter((lead) => String(lead.pageId) === String(page._id)); return <article key={page._id}><div className={styles.assetPreview}>{page.templateId?.thumbnailUrl ? <img src={page.templateId.thumbnailUrl} alt=""/> : <><span>mytiklink</span><b>{page.title || "Untitled page"}</b></>}</div><div className={styles.assetContent}><div><h3>{page.title || "Untitled page"}</h3><p>{page.slug ? `mytiklink.com/p/${page.slug}` : "Not published yet"}</p></div><Badge tone={page.slug ? "success" : "warning"}>{page.slug ? "Published" : "Draft"}</Badge><div className={styles.assetFacts}><button onClick={() => onLeads(page)}><b>{pageLeads.length}</b><small>Leads</small></button><span><b>{page.clickCount || page.views || 0}</b><small>Visits</small></span></div><div className={styles.assetActions}><Button variant="secondary" disabled={!page.slug} onClick={() => page.slug && window.open(`/p/${page.slug}`, "_blank")}>Preview</Button><Button onClick={() => router.push(`/v1-1/pages/editor?pageId=${page._id}`)}>Edit page</Button><Button variant="ghost" onClick={() => remove(page)}>Delete</Button></div></div></article>; })}</div> : <EmptyState icon="▣" title={query ? "No matching pages" : "Create your first landing page"} description={query ? "Try a different search." : "Start with a template for your offer or campaign, then decide what visitors should do next."} action={!query && <Button onClick={onCreate}>Choose a template</Button>}/>} 
  </div>;
}
