import { useRouter } from "next/router";
import { Badge, Button, EmptyState, PageHeader } from "../components/UI";
import { v11Routes } from "../config/routes";
import styles from "../styles/v11.module.css";

export function StorePage({ data }) {
  const router = useRouter();
  if (!data.store) return <div className={styles.page}><PageHeader eyebrow="STOREFRONT" title="Start selling online." description="Create a store where customers can browse your products and place orders—even while you’re offline."/><EmptyState icon="◇" title="Set up your storefront" description="Your Storefront is an independent product. You do not need a Landing Page or Smart Link to use it." action={<Button onClick={() => router.push("/v1-1/store/setup")}>Set up storefront</Button>}/></div>;
  const store = data.store, stats = data.storeStats || {};
  const pending = data.orders.filter((order) => ["new", "pending"].includes(String(order.status).toLowerCase()));
  const lowStock = data.products.filter((product) => Number(product.stock ?? product.quantity ?? 99) <= 3);
  const storeUrl = typeof window !== "undefined" ? `${window.location.origin}/s/${store.slug}` : `/s/${store.slug}`;
  return <div className={styles.page}><PageHeader eyebrow="STOREFRONT" title={store.businessName || store.name || "Your storefront"} description="Manage products, orders, design and store settings from one operational workspace." actions={<><Button variant="secondary" onClick={() => window.open(`/s/${store.slug}`, "_blank")}>View live store</Button><Button onClick={() => router.push(v11Routes.products)}>＋ Add product</Button></>}/><nav className={styles.localNav}><button className={styles.localActive}>Overview</button><button onClick={() => router.push(v11Routes.products)}>Products</button><button onClick={() => router.push(v11Routes.orders)}>Orders {pending.length ? <Badge tone="warning">{pending.length}</Badge> : null}</button><button onClick={() => router.push(v11Routes.storeDesign)}>Design</button><button onClick={() => router.push(v11Routes.storeSettings)}>Settings</button></nav>
    <section className={styles.storeHero}><div><Badge tone={store.isPublished === false ? "warning" : "success"}>{store.isPublished === false ? "Draft" : "Live"}</Badge><h2>Your storefront is {store.isPublished === false ? "almost ready" : "open"}.</h2><p>{storeUrl}</p><div><Button onClick={() => navigator.clipboard.writeText(storeUrl)}>Copy store link</Button><Button variant="secondary" onClick={() => window.open(`/s/${store.slug}`, "_blank")}>Preview store</Button></div></div><div className={styles.storePreview}><b>{store.businessName || store.name}</b><small>{store.description || "Browse our latest products"}</small><div>{data.products.slice(0, 4).map((product) => product.images?.[0] ? <img key={product._id} src={product.images[0]} alt=""/> : <span key={product._id}/>)}</div></div></section>
    <div className={styles.storeColumns}><section><div className={styles.sectionTitle}><h2>What needs attention</h2></div><div className={styles.taskList}><button onClick={() => router.push(v11Routes.orders)}><span>{pending.length}</span><div><b>Orders waiting for review</b><p>Confirm payment and keep customers updated.</p></div><strong>Review →</strong></button><button onClick={() => router.push(v11Routes.products)}><span>{lowStock.length}</span><div><b>Products low in stock</b><p>Update inventory before customers order.</p></div><strong>Update →</strong></button>{!pending.length && !lowStock.length && <div className={styles.quietTask}>Your store has no urgent tasks.</div>}</div></section><section><div className={styles.sectionTitle}><h2>Store activity</h2></div><div className={styles.storeMetrics}><div><span>Orders</span><b>{stats.totalOrders ?? data.orders.length}</b></div><div><span>Order value</span><b>₦{Number(stats.totalRevenue || stats.orderValue || 0).toLocaleString()}</b></div><div><span>Products</span><b>{data.products.length}</b></div><div><span>Store visits</span><b>{Number(stats.totalVisits || stats.visits || 0).toLocaleString()}</b></div></div></section></div>
  </div>;
}
